name: KiCAD Github Release

on: [push]

jobs:
  kicad:
    name: KiCAD Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install KiCAD tools
        run: git clone --branch=ci https://github.com/nnarain/kicad-tools /opt/kicad-tools
      - name: Install ZIP
        run: sudo apt install zip -qq -y
      - name: Generate KiCAD outputs
        env:
          DOCKER_CONTAINER: nnarain/kicad-tools
          DOCKER_INTERACTIVE: ""
          KICAD_TOOLS_PATH: /opt/kicad-tools
        run: cd design/esp-light-controller && make fabrication-outputs
      - name: List Output
        run: ls -R design/esp-light-controller/out
