name: KiCAD Github Release

on: [push]

jobs:
  kicad:
    name: KiCAD Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install KiCAD tools
        run: git clone https://github.com/nnarain/kicad-tools /opt/kicad-tools
      - name: Generate KiCAD outputs
        env:
          DOCKER_CONTAINER: nnarain/kicad-tools
        run: make -f design/esp-light-controller/Makefile
      - name: List Output
        run: ls design/esp-light-controller/out
