name: KiCAD Github Release

on: [push]

jobs:
  kicad:
    name: KiCAD Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install KiCAD tools
        run: git clone --branch=ci https://github.com/nnarain/kicad-tools /opt/kicad-tools
      - name: Generate KiCAD outputs
        env:
          DOCKER_CONTAINER: nnarain/kicad-tools
          DOCKER_INTERACTIVE: ""
          KICAD_TOOLS_PATH: /opt/kicad-tools
        run: cd design/esp-light-controller && make fabrication-outputs
      - name: List Output
        run: ls -R design/esp-light-controller/out
      - name: Grab Gerber files
        run: find . -type f \( -iname \*.gbr -iname \*.png \) -print | zip esp-light-controller-build-assets.zip -@
      - name: Grab BOM
        run: cp $(find . -name "bom.csv") bom.csv
      - name: List directory
        run: ls
