name: Release

# on:
#   push:
#     tags:
#       - '*'
on: [push]

jobs:
  kicad:
    name: KiCAD
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install KiCAD tools
        run: git clone --branch=ci https://github.com/nnarain/kicad-tools /opt/kicad-tools
      - name: Install third party KiCAD libraries
        run: mkdir -p /opt/kicad-libs && git clone https://github.com/nnarain/kicad-ESP8266.git /opt/kicad-libs/kicad-ESP8266
      - name: Generate KiCAD outputs
        env:
          DOCKER_CONTAINER: nnarain/kicad-tools
          DOCKER_INTERACTIVE: ""
          KICAD_TOOLS_PATH: /opt/kicad-tools
          KICAD_LIB_DIR: /opt/kicad-libs
        run: cd design/esp-light-controller && make fabrication-outputs
      - name: Collect Build Assets
        run: find . -type f \( -iname \*.gbr -o -iname \*.drl \) -print | zip esp-light-controller-build-assets.zip -@
      - name: Collect BOM
        run: cp $(find . -name "bom.csv") bom.csv
      - name: Collect Schematics
        run: cp $(find . -name "esp-light-controller.pdf") esp-light-controller.pdf
      - uses: actions/upload-artifact@master
        with:
          name: kicad
          path: esp-light-controller-build-assets.zip
      - uses: actions/upload-artifact@master
        with:
          name: kicad
          path: bom.csv
      - uses: actions/upload-artifact@master
        with:
          name: kicad
          path: esp-light-controller.pdf

  firmware:
    name: Firmware
    runs-on: ubuntu-latest

    steps:
      - run: echo "TODO"

  deploy:
    name: Deploy to Github Releases
    runs-on: ubuntu-latest
    needs: [kicad, firmware]

    steps:
      - uses: actions/download-artifact@master
        with:
          name: kicad
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            ./kicad/*
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
